Repository jsk-ros-pkg/coral_usb_ros, pull requests merged in 2020-10, with the labels that each got.

#34 add enable_visualization and visualization_duration params
  README.md
  media/edgetpu_semantic_segmenter.gif
  media/edgetpu_semantic_segmenter.png
  node_scripts/edgetpu_face_detector.py
  node_scripts/edgetpu_human_pose_estimator.py
  node_scripts/edgetpu_object_detector.py
  node_scripts/edgetpu_semantic_segmenter.py
Labels: enhancement

#35 add --gpu args in train.sh
  training/labelme_voc/run.sh
Labels: hacktoberfest-accepted

#36 fix run.sh to properly pass arguments
  training/epic_kitchens_55/run.sh
  training/epic_kitchens_55/scripts/train.sh
  training/labelme_voc/run.sh
  training/labelme_voc/scripts/train.sh
Labels: bug
